### ISSUE TITLE
issue related to the container

### ISSUE THREAD

**Issue by jmzoda** [rycus86/docker-pygen#1]
Hello,
When starting the docker container
`docker run -d --name config-generator                         \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v shared-volume:/etc/share/config              \
              -v $PWD/template.conf:/etc/share/template.conf  \
              --template /etc/share/template.conf             \
              --target   /etc/share/config/auto.conf          \
              --restart  config-loader                        \
              --signal   web-server HUP                       \
              rycus86/docker-pygen`
I get 
`unknown flag: --template`
`See 'docker run --help'.`
Proposal
What about a demo mode with default values, just to test docker-pygen ?
Thank you

**Comment by rycus86** [comment]
Hi,

Thanks for trying the app!
We need to know the template to use at least, which is a parameter for the app, so comes after the image name.
Try this:
`docker run -d --name config-generator \ -v /var/run/docker.sock:/var/run/docker.sock:ro \ -v shared-volume:/etc/share/config \ -v $PWD/template.conf:/etc/share/template.conf \ rycus86/docker-pygen --template /etc/share/template.conf \ --target /etc/share/config/auto.conf \ --restart config-loader \ --signal web-server HUP`

**Comment by jmzoda** [comment]
Thank you for sharing. That's an interesting project. 
That should be nice to update the README.md with your remark. 
My colleague also tried to run the image docker-pygen with his template but had an error. 
I'll have to check later.

**Comment by rycus86** [comment]
Sounds like a good idea!
I'll try to add some run examples.
Thanks!
